; << Generated by NadLabem >>
; the open source brandejs-to-assembly compiler

cpu 8086
segment code
..start mov  bx, data
        mov  ds, bx
        mov  ss, bx
        mov  es, bx
        mov  sp, dno
        mov  bp, sp

        jmp  over
put_char:
        push bp                  ;def put_char(character: char) -> void { (std/io.brandejs:1)
        mov  bp, sp
        sub  sp, 0
        mov ah, 2                ;    $ mov ah, 2     ; Identifikace služby Vypsat jeden bajt na terminál (std/io.brandejs:2)

        mov dl, byte[bp + 4]     ;    $ mov dl, byte[{character}]     ; Bajt, který se má na terminál vypsat (std/io.brandejs:3)

        int 0x21                 ;    $ int 0x21      ; resp. int 33 poskytne službu (std/io.brandejs:4)

rtn     mov  sp, bp
        pop  bp
        ret  2
over:

        jmp  over1
print:
        push bp                  ;def print(str: @char[]) -> void { (std/io.brandejs:70)
        mov  bp, sp
        sub  sp, 3
        mov  ax, 0               ;    i: int = 0 (std/io.brandejs:71)
        mov  word[bp - 2], ax

        mov  ax, 0               ;    character: char = str[0] (std/io.brandejs:72)
        mov  si, ax
        mov  bx, word[bp + 4]
        mov  ax, 0
        mov  al, byte[bx + si]
        mov  byte[bp - 3], al

while:                           ;    while(character != 0c){ (std/io.brandejs:73)
        mov  ax, 0
        mov  al, byte[bp - 3]
        push ax
        mov  ax, 0
        pop  bx
        cmp  ax, bx
        je   wout
        mov  ax, 0               ;        put_char(character) (std/io.brandejs:74)
        mov  al, byte[bp - 3]
        push ax
        call put_char

        lea  bx, [bp - 2]        ;        ++i (std/io.brandejs:75)
        inc  word[bx]

        mov  ax, word[bp - 2]    ;        character = str[i] (std/io.brandejs:76)
        mov  si, ax
        mov  bx, word[bp + 4]
        mov  ax, 0
        mov  al, byte[bx + si]
        mov  byte[bp - 3], al

        jmp  while
wout:

rtn1    mov  sp, bp
        pop  bp
        ret  2
over1:

        jmp  over2
println:
        push bp                  ;def println(str: @char[]) -> void { (std/io.brandejs:86)
        mov  bp, sp
        sub  sp, 0
        mov  ax, word[bp + 4]    ;    print(*str) (std/io.brandejs:87)
        push ax
        call print

        mov  ax, 13              ;    put_char(13c)   ; 13 - CR (std/io.brandejs:88)
        push ax
        call put_char

        mov  ax, 10              ;    put_char(10c)   ; 10 - LF (std/io.brandejs:89)
        push ax
        call put_char

rtn2    mov  sp, bp
        pop  bp
        ret  2
over2:

        jmp  over3
print_decimal:
        push bp                  ;def print_decimal(number: int) -> void { (std/io.brandejs:122)
        mov  bp, sp
        sub  sp, 4
        mov  ax, 0               ;    index: int = 0 (std/io.brandejs:123)
        mov  word[bp - 2], ax

while1:                          ;    do { (std/io.brandejs:125)
        mov  ax, 10              ;        last_digit: int = number % 10 (std/io.brandejs:126)
        push ax
        mov  ax, word[bp + 4]
        pop  bx
        mov  dx, 0
        div  bx
        mov  ax, dx
        mov  word[bp - 4], ax

        mov  ax, 48              ;        print_decimal.DIGITS[index] = last_digit :: char + '0' (std/io.brandejs:127)
        push ax
        mov  ax, word[bp - 4]
        mov  ah, 0
        pop  bx
        add  ax, bx
        push ax
        mov  ax, word[bp - 2]
        mov  si, ax
        pop  ax
        mov  byte[DIGITS + si], al

        mov  ax, 10              ;        number = number / 10 (std/io.brandejs:128)
        push ax
        mov  ax, word[bp + 4]
        pop  bx
        mov  dx, 0
        div  bx
        mov  word[bp + 4], ax

        lea  bx, [bp - 2]        ;        ++index (std/io.brandejs:129)
        inc  word[bx]

        mov  ax, word[bp + 4]    ;    } while (number > 0) (std/io.brandejs:130)
        push ax
        mov  ax, 0
        pop  bx
        cmp  ax, bx
        jb   while1
wout1:

while2:                          ;    while (index > 0) { (std/io.brandejs:133)
        mov  ax, word[bp - 2]
        push ax
        mov  ax, 0
        pop  bx
        cmp  ax, bx
        jae  wout2
        lea  bx, [bp - 2]        ;        --index (std/io.brandejs:134)
        dec  word[bx]

        mov  ax, word[bp - 2]    ;        put_char(print_decimal.DIGITS[index]) (std/io.brandejs:135)
        mov  si, ax
        mov  ax, 0
        mov  al, byte[DIGITS + si]
        push ax
        call put_char

        jmp  while2
wout2:

rtn3    mov  sp, bp
        pop  bp
        ret  2
over3:

        mov  ax, 5               ;result: int = fact(5) (factorial.bjs:12)
        push ax
        call fact
        mov  word[result], ax
        lea  ax, [_str]          ;io.print(*"Factorial of 5 is: ") (factorial.bjs:15)
        push ax
        call print
        mov  ax, word[result]    ;io.print_decimal(result) (factorial.bjs:16)
        push ax
        call print_decimal
        lea  ax, [_str1]         ;io.println(*"") (factorial.bjs:17)
        push ax
        call println
exit:
ok      hlt
error   hlt

        jmp  over4
fact:
        push bp                  ;def fact(num: int) -> int { (factorial.bjs:4)
        mov  bp, sp
        sub  sp, 0
        mov  ax, word[bp + 4]    ;    if (num <= 1) { (factorial.bjs:5)
        push ax
        mov  ax, 1
        pop  bx
        cmp  ax, bx
        jb   ifout
        mov  ax, 1               ;        return 1 (factorial.bjs:6)
        jmp  rtn4

ifout:

        mov  ax, 1               ;    return num * fact(num - 1) (factorial.bjs:8)
        push ax
        mov  ax, word[bp + 4]
        pop  bx
        sub  ax, bx
        push ax
        call fact
        push ax
        mov  ax, word[bp + 4]
        pop  bx
        mul  bx
        jmp  rtn4

rtn4    mov  sp, bp
        pop  bp
        ret  2
over4:
true    mov  ax, 1
        or   ax, ax
        ret
false   mov  ax, 0
        or   ax, ax
        ret

segment data
stack   resw 1024
dno     db   ?

_str    db   "Factorial of 5 is: ", 0
_str1   db   0
DIGITS  resb 6
result  resb 2                   ;default