; << Generated by NadLabem >>
; the open source brandejs-to-assembly compiler

cpu 8086
segment code
..start mov  bx, heap
        mov  ds, bx
        mov  es, bx
        mov  bx, stack
        mov  ss, bx
        mov  sp, dno
        mov  bp, sp

        mov  ax, 5               ;x:int = 5 (1)
        mov  word[x], ax
        lea  bx, [x]             ;++x (2)
        inc  word[bx]
        mov ax, word[x]
exit:
ok      hlt
error   hlt

segment heap
stack   resw 1024
dno     db   ?

x       resb 2                   ;default